/*
 * Question pairs for Odd Question.
 * "main" goes to most players, "odd" goes to the odd one out.
 * Both questions should have the same kind of answer (a number, a place,
 * a food...) so the odd answer is plausible but a little off.
 */
window.ODD_QUESTIONS = [
  { main: "How many hours do you sleep per night?", odd: "How many hours do you spend on your phone per day?" },
  { main: "How many cups of coffee do you drink per day?", odd: "How many times do you wash your hands per day?" },
  { main: "What is your favourite pizza topping?", odd: "What food would you never eat again?" },
  { main: "How old were you when you got your first phone?", odd: "What age do you want to retire at?" },
  { main: "How many pairs of shoes do you own?", odd: "How many countries have you visited?" },
  { main: "Where would you go on your dream holiday?", odd: "Where would you hide during a zombie apocalypse?" },
  { main: "What animal would you like as a pet?", odd: "What animal are you most scared of?" },
  { main: "How many minutes do you spend in the shower?", odd: "How many minutes does it take you to get to work or school?" },
  { main: "What is your favourite season of the year?", odd: "Which season do you think is the most overrated?" },
  { main: "How many apps are on your phone's home screen?", odd: "How many unread emails do you have?" },
  { main: "What's the best movie you've ever seen?", odd: "What movie made you fall asleep?" },
  { main: "How many times a week do you exercise?", odd: "How many times a week do you eat takeaway?" },
  { main: "What would you buy first if you won the lottery?", odd: "What is the most useless thing you own?" },
  { main: "How many people are in your contacts list?", odd: "How many people would you invite to your wedding?" },
  { main: "What's your favourite thing to eat for breakfast?", odd: "What do you eat when you're sad?" },
  { main: "What celebrity would you like to have dinner with?", odd: "What celebrity do you find most annoying?" },
  { main: "How much would you pay for a concert ticket?", odd: "How much did your last haircut cost?" },
  { main: "What is your dream job?", odd: "What job would you be terrible at?" },
  { main: "Which superpower would you choose?", odd: "Which superpower would be the most useless?" },
  { main: "What's your favourite colour?", odd: "What colour would you never paint your bedroom?" },
  { main: "At what time do you usually wake up?", odd: "At what time do you usually eat dinner?" },
  { main: "Which city would you most like to live in?", odd: "Which city would you least like to live in?" },
  { main: "How many siblings would you like to have?", odd: "How many kids would you like to have?" },
  { main: "What's the best smell in the world?", odd: "What's a smell that reminds you of your childhood?" },
  { main: "What song always gets you dancing?", odd: "What song would you play at a funeral?" },
  { main: "How many hours could you go without checking your phone?", odd: "How many hours could you survive without eating?" },
  { main: "What's your go-to karaoke song?", odd: "What song is stuck in your head the most?" },
  { main: "What's the best gift you've ever received?", odd: "What's the worst gift you've ever received?" },
  { main: "Which sport would you like to be a pro at?", odd: "Which sport is the most boring to watch?" },
  { main: "How many books do you read in a year?", odd: "How many times a year do you go to the dentist?" },
  { main: "What's the first thing you do in the morning?", odd: "What's the last thing you do before bed?" },
  { main: "What would be your last meal?", odd: "What food would you bring to a picnic?" },
  { main: "How many tabs do you have open in your browser right now?", odd: "How many friends do you text every day?" },
  { main: "What's the best board game ever?", odd: "What game always ends in an argument?" },
  { main: "Which historical period would you visit with a time machine?", odd: "In which historical period would you not survive a day?" },
  { main: "What's your favourite ice cream flavour?", odd: "What's the strangest ice cream flavour you can imagine?" },
  { main: "How many kilometres could you walk in one day?", odd: "How many kilometres do you live from where you were born?" },
  { main: "What do you always pack for a holiday?", odd: "What do you always forget to pack?" },
  { main: "Which fictional character would you like as a best friend?", odd: "Which fictional character would make a terrible roommate?" },
  { main: "How much money would you need to feel rich?", odd: "How much would you pay for a really good mattress?" },
  { main: "What's a hobby you'd love to pick up?", odd: "What's a hobby you gave up on?" },
  { main: "What's the best place to go on a first date?", odd: "Where would you go to be alone?" },
  { main: "How many hours of TV do you watch per week?", odd: "How many hours do you spend cooking per week?" },
  { main: "What's your favourite type of weather?", odd: "What weather makes you stay inside all day?" },
  { main: "Which language would you like to learn?", odd: "Which language sounds the funniest to you?" },
  { main: "What age do you feel like inside?", odd: "What age were you at your most embarrassing?" },
  { main: "What would you name a boat?", odd: "What would you name a pet goldfish?" },
  { main: "What's the most you've ever spent on a meal?", odd: "What's the most you'd pay for a pair of jeans?" },
  { main: "What snack would you take to the cinema?", odd: "What snack do you hide from other people?" },
  { main: "How many times have you moved house?", odd: "How many times have you broken a phone screen?" }
];
