/*
 * Question pairs for Odd Question.
 * "main" goes to most players, "odd" goes to the odd one out.
 * Both questions should have the same kind of answer (a number, a place,
 * a food...) so the odd answer is plausible but a little off.
 */
window.ODD_QUESTIONS = [
    { main: "How many hours do you sleep per night?", odd: "How many hours do you spend on your phone per day?" },
  { main: "How many glasses of water do you drink per day?", odd: "How many times do you eat per day, snacks included?" },
  { main: "How many alarms do you set in the morning?", odd: "How many times do you hit snooze in the morning?" },
  { main: "How many countries have you visited?", odd: "In how many languages can you say a full sentence?" },
  { main: "How many hours a week do you spend gaming?", odd: "How many hours a week do you spend watching YouTube or streams?" },
  { main: "How many browser tabs do you usually have open?", odd: "How many unread notifications do you usually have?" },
  { main: "How many games do you own on your main platform?", odd: "How many games have you finished in your life?" },
  { main: "At what age did you get your first phone?", odd: "At what age did you get your first console or gaming PC?" },
  { main: "How many minutes does your shower take?", odd: "How many minutes does it take you to get out of bed after waking up?" },
  { main: "How many hours could you last without your phone?", odd: "How many hours could you last without talking to anyone?" },
  { main: "Out of 10, how good of a driver are you (or would you be)?", odd: "Out of 10, how good of a cook are you?" },
  { main: "Out of 10, how smart do you think you are?", odd: "Out of 10, how funny do you think you are?" },
  { main: "How many push-ups can you do in a row?", odd: "How many sit-ups can you do in a row?" },
  { main: "How many pairs of shoes do you own?", odd: "How many hoodies and jackets do you own?" },
  { main: "What time do you usually go to sleep?", odd: "What time do you usually stop gaming at night?" },
  { main: "What time do you wake up on a weekend?", odd: "What time do you eat your first meal on a weekend?" },
  { main: "What is the most you would pay for a single game?", odd: "What is the most you would pay for a pair of shoes?" },
  { main: "How many hours was your longest gaming session?", odd: "How many hours was your longest trip by car, bus or train?" },
  { main: "How many soft drinks do you have per week?", odd: "How many coffees or energy drinks do you have per week?" },
  { main: "How many kilometers could you run without stopping?", odd: "How many kilometers do you walk on an average day?" },
  { main: "How many people in this room could you beat in a fight?", odd: "How many people in this room could you beat at chess?" },
  { main: "How many days could you survive alone in the woods?", odd: "How many days could you go without showering before it bothers you?" },
  { main: "How many group chats are you in?", odd: "How many Discord servers are you active in?" },
  { main: "At what age do you want to retire?", odd: "At what age is someone officially 'old'?" },
  { main: "How many times a week do you exercise?", odd: "How many times a week do you cook your own meal?" },
  { main: "How many books have you read in the last year?", odd: "How many series have you finished in the last year?" },
  { main: "How many minutes late are you usually?", odd: "How many minutes before leaving do you start getting ready?" },
  { main: "How many years have you been gaming?", odd: "How many years have you known your oldest friend in this room?" },
  { main: "Out of 10, how much do you like your job or studies?", odd: "Out of 10, how stressed were you last week?" },
  { main: "How many slices of pizza can you eat in one sitting?", odd: "How many pancakes can you eat in one sitting?" },
  { main: "How many hours a day do you spend sitting at a desk?", odd: "How many hours a day do you spend on a PC?" },
  { main: "How many times a year do you get sick?", odd: "How many times a year do you go to a doctor or dentist?" },
  { main: "How many different passwords do you actually use?", odd: "How many email accounts do you have?" },
  { main: "Out of 10, how good are you at shooters?", odd: "Out of 10, how good are you at strategy games?" },
  { main: "How many hours can you sit at your desk without getting up?", odd: "How many hours can you focus on one task?" },
  { main: "How many millions would you need to never work again?", odd: "How many millions would it take for you to never play a video game again?" },
  { main: "How many people do you message on a normal day?", odd: "How many people do you talk to in person on a normal day?" },
  { main: "How many minutes can you talk to a stranger before it gets awkward?", odd: "How many minutes of a lecture or meeting can you actually pay attention to?" },
  { main: "What was the best year of your life so far?", odd: "In what year did the best game of all time come out?" },
  { main: "How many screens do you own (phones, monitors, TVs, everything)?", odd: "How many controllers, keyboards and mice do you own in total?" },
 
  // ───────────── WHO IN THIS ROOM (60) ─────────────
  { main: "Who in this room would survive the longest in a zombie apocalypse?", odd: "Who in this room would you want on your team in a zombie apocalypse?" },
  { main: "Who in this room is the best gamer?", odd: "Who in this room is the most competitive?" },
  { main: "Who in this room would die first in a horror movie?", odd: "Who in this room gets scared the easiest?" },
  { main: "Who in this room is most likely to become rich?", odd: "Who in this room is the smartest?" },
  { main: "Who in this room is the worst driver?", odd: "Who in this room would you least trust to fly a plane?" },
  { main: "Who in this room is always late?", odd: "Who in this room takes the longest to reply to messages?" },
  { main: "Who in this room rages the most at games?", odd: "Who in this room is the loudest?" },
  { main: "Who in this room would win in a fight?", odd: "Who in this room is the strongest?" },
  { main: "Who in this room would make the best president?", odd: "Who in this room would make the best boss?" },
  { main: "Who in this room is most likely to end up in jail?", odd: "Who in this room is most likely to get banned from a game?" },
  { main: "Who in this room eats the most?", odd: "Who in this room eats the fastest?" },
  { main: "Who in this room has the weirdest taste in music?", odd: "Who in this room has the weirdest taste in games?" },
  { main: "Who in this room spends the most money on games?", odd: "Who in this room has the most hours in a single game?" },
  { main: "Who in this room would survive the longest without internet?", odd: "Who in this room would be the best at camping?" },
  { main: "Who in this room is the funniest?", odd: "Who in this room laughs the most?" },
  { main: "Who in this room would you pick as your teammate in a 2v2?", odd: "Who in this room would you pick to carry you in a ranked match?" },
  { main: "Who in this room would fall asleep first at a sleepover?", odd: "Who in this room would leave a party first?" },
  { main: "Who in this room knows the most useless facts?", odd: "Who in this room would win a quiz?" },
  { main: "Who in this room is the most stubborn?", odd: "Who in this room argues the most?" },
  { main: "Who in this room is the best liar?", odd: "Who in this room would be the best impostor in Among Us?" },
  { main: "Who in this room is the worst liar?", odd: "Who in this room is the easiest to read?" },
  { main: "Who in this room would be the best streamer?", odd: "Who in this room talks the most?" },
  { main: "Who in this room is the most organized?", odd: "Who in this room has the cleanest room?" },
  { main: "Who in this room has the messiest desk?", odd: "Who in this room is the laziest?" },
  { main: "Who in this room is most likely to become famous?", odd: "Who in this room is most likely to go viral for something stupid?" },
  { main: "Who in this room is the biggest nerd?", odd: "Who in this room knows the most about computers?" },
  { main: "Who in this room would win at Mario Kart?", odd: "Who in this room would win a real go-kart race?" },
  { main: "Who in this room is the cheapest?", odd: "Who in this room is the best at saving money?" },
  { main: "Who in this room would last the longest on a deserted island?", odd: "Who in this room would become the leader on a deserted island?" },
  { main: "Who in this room would you call to fix your PC?", odd: "Who in this room would you call if you were stuck on a hard puzzle?" },
  { main: "Who in this room is most likely to forget a birthday?", odd: "Who in this room is most likely to lose their keys?" },
  { main: "Who in this room has the best memory?", odd: "Who in this room is the best at mental math?" },
  { main: "Who in this room is the most patient?", odd: "Who in this room is the calmest under pressure?" },
  { main: "Who in this room would be the best teacher?", odd: "Who in this room is the best at explaining the rules of a board game?" },
  { main: "Who in this room is most likely to rage quit?", odd: "Who in this room is most likely to blame their teammates?" },
  { main: "Who in this room would be the villain in a movie?", odd: "Who in this room would be the mastermind in a heist?" },
  { main: "Who in this room would be the hero in a movie?", odd: "Who in this room would survive until the end of a movie?" },
  { main: "Who in this room is most likely to move abroad?", odd: "Who in this room is most likely to travel the world?" },
  { main: "Who in this room will still be gaming at age 70?", odd: "Who in this room will have the exact same hobbies in 20 years?" },
  { main: "Who in this room goes to sleep the latest?", odd: "Who in this room is most likely to pull an all-nighter?" },
  { main: "Who in this room would win at poker?", odd: "Who in this room is the luckiest?" },
  { main: "Who in this room is the worst with directions?", odd: "Who in this room is most likely to get lost in a foreign city?" },
  { main: "Who in this room is the most addicted to their phone?", odd: "Who in this room watches the most YouTube?" },
  { main: "Who in this room is most likely to buy something dumb online?", odd: "Who in this room is most likely to pre-order a bad game?" },
  { main: "Who in this room has the best gaming setup?", odd: "Who in this room has spent the most money on their PC or console?" },
  { main: "Who in this room is the best cook?", odd: "Who in this room would be the best at running a restaurant?" },
  { main: "Who in this room is most likely to cry at a movie?", odd: "Who in this room is most likely to scream at a jump scare?" },
  { main: "Who in this room would win a staring contest?", odd: "Who in this room could stay silent the longest?" },
  { main: "Who in this room is most likely to start their own company?", odd: "Who in this room is most likely to invent something?" },
  { main: "Who in this room is the best at keeping secrets?", odd: "Who in this room would you trust with your passwords?" },
  { main: "Who in this room would win a real-life battle royale?", odd: "Who in this room would hide in a bush the whole game and somehow win?" },
  { main: "Who in this room actually reads the manual?", odd: "Who in this room would actually read the terms and conditions?" },
  { main: "Who in this room would you swap lives with for a week?", odd: "Whose daily routine in this room would you want to have?" },
  { main: "Who in this room has the best taste in games?", odd: "Who in this room would you trust to recommend you a movie?" },
  { main: "Who in this room is the best at board games?", odd: "Who in this room takes board games the most seriously?" },
  { main: "Who in this room would be the best D&D dungeon master?", odd: "Who in this room is the best at telling a story?" },
  { main: "Who in this room is most likely to correct your grammar?", odd: "Who in this room is most likely to say 'well, actually...'?" },
  { main: "Who in this room has the most obscure hobby?", odd: "Who in this room knows the most about one very specific topic?" },
  { main: "Who in this room would be the best in an escape room?", odd: "Who in this room would solve a murder mystery first?" },
  { main: "Who in this room is most likely to forget to eat because of gaming?", odd: "Who in this room is most likely to forget what day it is?" },
 
  // ───────────── VIDEOGAMES (35) ─────────────
  { main: "Which game have you spent the most hours in?", odd: "Which game have you been playing for the most years?" },
  { main: "What was the first game you ever played?", odd: "What was your favorite game as a kid?" },
  { main: "Which game world would you want to live in?", odd: "Which game has the best world or map?" },
  { main: "Which game character would you want as a roommate?", odd: "Which game character would you want as a bodyguard?" },
  { main: "Which game made you rage the most?", odd: "What is the hardest game you have ever finished?" },
  { main: "Which game has the best soundtrack?", odd: "Which game is the most nostalgic for you?" },
  { main: "Which game would you erase from your memory to play it again for the first time?", odd: "Which game has the best story?" },
  { main: "Which game is the most overrated?", odd: "Which very popular game have you never played?" },
  { main: "Which game franchise is the best?", odd: "Which game franchise have you played the most entries of?" },
  { main: "What is the best console of all time?", odd: "What was the first console you owned?" },
  { main: "Which game genre do you play the most?", odd: "Which game genre are you the best at?" },
  { main: "Which type of weapon do you always pick in games?", odd: "Which weapon would you pick in a zombie apocalypse?" },
  { main: "Which class do you pick in an RPG?", odd: "Which RPG class fits your real personality?" },
  { main: "Which Pokémon would you want as a pet?", odd: "Which Pokémon is your favorite?" },
  { main: "Which character do you pick in Mario Kart?", odd: "Which Mario character is the best?" },
  { main: "Which game boss was the hardest for you?", odd: "Which game boss is the most memorable?" },
  { main: "Which game has the best multiplayer?", odd: "Which game have you played the most with friends?" },
  { main: "Which game would you recommend to someone who never games?", odd: "Which game is the best to play together on one couch?" },
  { main: "Which game has the best graphics?", odd: "Which game impressed you the most when it came out?" },
  { main: "Who is the best video game villain?", odd: "Who is the coolest video game character?" },
  { main: "Which Minecraft mob is the most annoying?", odd: "Which Minecraft mob is the scariest?" },
  { main: "Which game do you always come back to?", odd: "Which game have you played the most this year?" },
  { main: "Which game studio do you trust the most?", odd: "Which game studio has made the most good games?" },
  { main: "Which game had the most disappointing launch?", odd: "Which game do you regret buying?" },
  { main: "Which game would make the best movie or series?", odd: "Which game has the best lore?" },
  { main: "Which map from any game do you know the best?", odd: "Which map from any game is the best ever made?" },
  { main: "Which game is the scariest?", odd: "Which game would you never play alone at night?" },
  { main: "Which mobile game have you played the most?", odd: "Which free-to-play game have you spent the most time or money on?" },
  { main: "Which game has the most toxic community?", odd: "In which game do you mute voice chat the most?" },
  { main: "Which game are you the best at?", odd: "In which game did you reach your highest rank?" },
  { main: "Which retro game is the best?", odd: "Which game that is older than you have you played?" },
  { main: "Which game deserves a sequel?", odd: "Which game deserves a remake?" },
  { main: "Which item from a game would you want in real life?", odd: "Which ability from a game would you want in real life?" },
  { main: "Which role do you usually play in a team game?", odd: "Which role do you end up playing when nobody else wants it?" },
  { main: "Which game are you looking forward to the most?", odd: "Which game would you get right now if it were free?" },
 
  // ───────────── GENERAL / LIFE (65) ─────────────
  { main: "Which animal would you want as a pet if anything was possible?", odd: "Which animal is the coolest?" },
  { main: "What is the biggest animal you think you could beat in a fight?", odd: "What is the biggest animal you would dare to pet?" },
  { main: "Which superpower would you want?", odd: "Which superpower would be the most useful in daily life?" },
  { main: "Which country would you want to live in?", odd: "Which country do you want to visit next?" },
  { main: "What is the best city you have visited?", odd: "Which city would you move to?" },
  { main: "Which language would you want to speak fluently?", odd: "Which language sounds the coolest?" },
  { main: "Which food could you eat every day?", odd: "Which food do you actually eat the most often?" },
  { main: "Which fast food chain is the best?", odd: "Which fast food chain did you eat at most recently?" },
  { main: "What is the best pizza topping?", odd: "Which pizza do you always order?" },
  { main: "What do you usually order to drink when you go out?", odd: "What do you drink the most at home?" },
  { main: "What is your go-to snack while gaming?", odd: "What is your go-to snack at the cinema?" },
  { main: "What do you eat when you are too lazy to cook?", odd: "What do you eat when you get hungry at 2 AM?" },
  { main: "Which school subject were you the best at?", odd: "Which school subject did you like the most?" },
  { main: "Which school subject were you the worst at?", odd: "Which school subject was the most useless?" },
  { main: "Which job would you do if money did not matter?", odd: "What was your dream job as a kid?" },
  { main: "Which job could you never do?", odd: "Which job seems the most stressful?" },
  { main: "Which movie have you seen the most times?", odd: "Which movie would you recommend to everyone?" },
  { main: "Which series would you rewatch?", odd: "Which series did you binge the fastest?" },
  { main: "Which movie or series character are you the most like?", odd: "Which movie or series character would you want to be?" },
  { main: "Which fictional universe would you want to live in?", odd: "In which fictional universe would you survive the longest?" },
  { main: "Which YouTuber have you watched the most?", odd: "Which YouTuber have you been watching for the longest time?" },
  { main: "Which app do you use the most?", odd: "Which app do you open first in the morning?" },
  { main: "Which social media wastes the most of your time?", odd: "Which social media would you delete from the world?" },
  { main: "Which tech company do you like the most?", odd: "Which tech company makes the best products?" },
  { main: "What is the most important invention ever?", odd: "Which invention could you not live without?" },
  { main: "Which historical period would you want to visit?", odd: "Which historical period is the most interesting?" },
  { main: "Which historical figure would you want to have dinner with?", odd: "Which historical figure is the most interesting?" },
  { main: "Which sport do you like watching the most?", odd: "Which sport would you be the best at?" },
  { main: "Which sport is the most boring?", odd: "Which sport do you not understand at all?" },
  { main: "Which month is the best?", odd: "In which month do you have the most free time?" },
  { main: "Which day of the week is the best?", odd: "On which day of the week do you game the most?" },
  { main: "Which household chore do you hate the most?", odd: "Which household chore do you postpone the longest?" },
  { main: "What would you buy first if you won the lottery?", odd: "What is the most expensive thing you want right now?" },
  { main: "What is the best thing you bought in the last year?", odd: "What is the most expensive thing you bought in the last year?" },
  { main: "What is your favorite color?", odd: "Which color do you wear the most?" },
  { main: "Which music genre do you listen to the most?", odd: "Which music genre do you listen to while gaming or working?" },
  { main: "Which artist or band have you listened to the most?", odd: "Which artist or band would you want to see live?" },
  { main: "Which song do you know all the lyrics to?", odd: "Which song have you had on repeat the most?" },
  { main: "Which instrument would you want to be able to play?", odd: "Which instrument sounds the best?" },
  { main: "Which skill would you want to master instantly?", odd: "Which skill do you wish you had learned as a kid?" },
  { main: "Which hobby would you pick up if you had unlimited time?", odd: "Which hobby did you start and then quit?" },
  { main: "Which board game is the best?", odd: "Which board game have you played the most?" },
  { main: "Which car would you buy with unlimited money?", odd: "Which car looks the best?" },
  { main: "Which type of transport do you use the most?", odd: "What is your favorite way to travel?" },
  { main: "Which animal or insect scares you the most?", odd: "Which animal or insect do you hate the most?" },
  { main: "What is the perfect outside temperature (°C)?", odd: "What temperature do you want your room to be (°C)?" },
  { main: "Which planet would you want to visit?", odd: "Which planet is the coolest?" },
  { main: "Which mythical creature do you wish was real?", odd: "Which mythical creature would you want as a pet?" },
  { main: "Which decade had the best music?", odd: "Which decade would you have wanted to grow up in?" },
  { main: "Which emoji do you use the most?", odd: "Which emoji describes you the best?" },
  { main: "What is the best ice cream flavor?", odd: "Which ice cream flavor do you always end up picking?" },
  { main: "What is the best fruit?", odd: "Which fruit do you eat the most?" },
  { main: "What is the worst vegetable?", odd: "Which food did you hate as a kid?" },
  { main: "Which country has the best food?", odd: "Which country's food could you eat for a whole month?" },
  { main: "What is the best chips flavor?", odd: "Which chips do you always buy?" },
  { main: "What is the best soda or energy drink?", odd: "Which soda or energy drink did you have most recently?" },
  { main: "Which topic could you talk about for an hour without preparing?", odd: "Which topic have you watched the most videos about?" },
  { main: "Which conspiracy theory is the most fun?", odd: "Which conspiracy theory is the most believable?" },
  { main: "Which fictional character would win a fight against anyone?", odd: "Which fictional character is the coolest?" },
  { main: "Which superhero is the best?", odd: "Which superhero would you want to be?" },
  { main: "Which cartoon or anime did you watch the most as a kid?", odd: "Which cartoon or anime from your childhood would you still watch today?" },
  { main: "Which movie franchise is the best?", odd: "Which movie franchise have you seen every part of?" },
  { main: "Which one item would you bring to a deserted island?", odd: "Which one item would you bring on a week-long camping trip?" },
  { main: "What do you do when the internet is down?", odd: "What do you do on a long train or plane ride?" },
  { main: "What would you do with a week off and no plans?", odd: "What do you do on a typical Sunday?" },
];
